### ISSUE TITLE
Build is failing on Windows

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#1041]
I've tried to build the latest version of the project on Windows 10 running this command:
```
mvn clean install -Pqulice
```
but I got 6 test failures. 5 failed tests are:

- com.zerocracy.tk.project.TkArtifactTest#rendersHomePage
- com.zerocracy.tk.project.TkFootprintTest#rendersListOfClaims
- com.zerocracy.pm.cost.EquityTest#addValue
- com.zerocracy.tk.TkAppTest#rendersHomePageViaHttp
- com.zerocracy.tk.profile.TkIdentifyTest#rendersHomePage

and have the same assertion error:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.871 sec <<< FAILURE! - in com.zerocracy.tk.profile.TkIdentifyTest
rendersHomePage(com.zerocracy.tk.profile.TkIdentifyTest)  Time elapsed: 0.871 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: (an XML document with XPath //xhtml:article)
     but: an XML document with XPath //xhtml:article was <<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8"/>
        <title>0crat: error</title>
        <meta name="description" content="Internal application error"/>
        <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
        <link rel="shortcut icon" href="/png/logo.png"/>
        <link rel="stylesheet" href="/css/main.css"/>
        <title>oops...</title>
    </head>
    <body>
        <p>
            <a href="/">
                <img src="/svg/logo.svg" class="logo" />
            </a>
        </p>
        <h1>Internal application error</h1>
        <p>1.0-SNAPSHOT, </p>
        <p>
            Please, report it
            <a href="https://github.com/zerocracy/farm/issues">here</a>.
            We will do our best to fix it as soon as possible.
            We're very sorry.
        </p>
        <pre>java.lang.IllegalStateException: [GET http://www.example.com/identify] failed in 35ms: ValidationException: Cannot convert string &quot;-1,000&quot; to double
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:91)
	at com.zerocracy.tk.profile.TkIdentifyTest.rendersHomePage(TkIdentifyTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: ValidationException: Cannot convert string &quot;-1,000&quot; to double
	at org.takes.rs.RsXslt.transform(RsXslt.java:133)
	at org.takes.rs.RsXslt.access$100(RsXslt.java:89)
	at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 22 more
Caused by: ValidationException: Cannot convert string &quot;-1,000&quot; to double
	at net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:393)
	at net.sf.saxon.type.ValidationFailure.asAtomic(ValidationFailure.java:419)
	at net.sf.saxon.expr.sort.UntypedNumericComparer.quickComparison(UntypedNumericComparer.java:159)
	at net.sf.saxon.expr.sort.UntypedNumericComparer.quickCompare(UntypedNumericComparer.java:59)
	at net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:833)
	at net.sf.saxon.expr.GeneralComparison.evaluateManyToOne(GeneralComparison.java:711)
	at net.sf.saxon.expr.GeneralComparison.effectiveBooleanValue(GeneralComparison.java:660)
	at net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902)
	at net.sf.saxon.expr.instruct.Choose.iterate(Choose.java:953)
	at net.sf.saxon.expr.instruct.BlockIterator.next(BlockIterator.java:49)
	at net.sf.saxon.tree.iter.AdjacentTextNodeMergingIterator.next(AdjacentTextNodeMergingIterator.java:52)
	at net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:50)
	at net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:32)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:108)
	at net.sf.saxon.functions.FoldingFunction.call(FoldingFunction.java:59)
	at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:547)
	at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:831)
	at net.sf.saxon.expr.Expression.evaluateAsString(Expression.java:890)
	at net.sf.saxon.expr.instruct.SimpleNodeConstructor.processLeavingTail(SimpleNodeConstructor.java:218)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:262)
	at net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
	at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:478)
	at net.sf.saxon.Controller.transformDocument(Controller.java:2402)
	at net.sf.saxon.Controller.transform(Controller.java:1970)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)
	at org.takes.rs.RsXslt.transform(RsXslt.java:160)
	at org.takes.rs.RsXslt.transform(RsXslt.java:131)
	... 44 more
</pre>
    </body>
</html>
>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.zerocracy.tk.profile.TkIdentifyTest.rendersHomePage(TkIdentifyTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

And then there is the 6th failed test:

- com.zerocracy.farm.S3ItemTest#refreshesFilesOnServer

that has another cause:
```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.122 sec <<< FAILURE! - in com.zerocracy.farm.S3ItemTest
refreshesFilesOnServer(com.zerocracy.farm.S3ItemTest)  Time elapsed: 0.121 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: not an empty iterable
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.zerocracy.farm.S3ItemTest.refreshesFilesOnServer(S3ItemTest.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I guess it's somehow related to my current locale that is the following:
![image](https://user-images.githubusercontent.com/3031372/40388406-1c269e46-5e18-11e8-91e8-26b0875b1a30.png)

**TODO:**
- fix the build on Windows OS

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1041](https://github.com/zerocracy/farm/issues/1041) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by krzyk** [comment]
@g4s8 could I take this one? (it really annoys me that appveyor always fails)

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1041#issuecomment-398064058))

@g4s8 The job [#1041](https://github.com/zerocracy/farm/issues/1041) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1691402351); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@proshin-roman the puzzle [#1231](https://github.com/zerocracy/farm/issues/1231) is still not solved.

**Comment by g4s8** [comment]
@proshin-roman please, try now. It should be fixed in #1178

**Comment by proshin-roman** [comment]
@g4s8 I've tried to build the latest master with command `mvn clean install --batch-mode -Pqulice` and got a few failures:
```
Failed tests: 
  TkBoardTest.rendersBoardWithFundedProject:69 
Expected: (an XML document with XPath //xhtml:span[@title = 'The project is funded' and . = '$256.00'])
     but: an XML document with XPath //xhtml:span[@title = 'The project is funded' and . = '$256.00'] was "<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n    <head>\n        <meta charset=\"utf-8\"/>\n        <title>0crat: error</title>\n        <meta name=\"description\" content=\"Internal application error\"/>\n        <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\"/>\n        <link rel=\"shortcut icon\" href=\"/png/logo.png\"/>\n        <link rel=\"stylesheet\" href=\"/css/main.css\"/>\n        <title>oops...</title>\n    </head>\n    <body>\n        <p>\n            <a href=\"/\">\n                <img src=\"/svg/logo.svg\" class=\"logo\" />\n            </a>\n        </p>\n        <h1>Internal application error</h1>\n        <p>1.0-SNAPSHOT, </p>\n        <p>\n            Please, report it\n            <a href=\"https://github.com/zerocracy/farm/issues\">here</a>.\n            We will do our best to fix it as soon as possible.\n            We're very sorry.\n        </p>\n        <pre>java.lang.IllegalStateException: [GET http://www.example.com/board] failed in 194ms: ValidationException: Cannot convert string &quot;-1,000&quot; to double\r\n\tat org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)\r\n\tat org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)\r\n\tat org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsPrint.printBody(RsPrint.java:161)\r\n\tat org.takes.rs.RsPrint.printBody(RsPrint.java:91)\r\n\tat com.zerocracy.tk.TkBoardTest.firefoxView(TkBoardTest.java:120)\r\n\tat com.zerocracy.tk.TkBoardTest.rendersBoardWithFundedProject(TkBoardTest.java:70)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\r\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\r\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\r\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\r\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.io.IOException: ValidationException: Cannot convert string &quot;-1,000&quot; to double\r\n\tat org.takes.rs.RsXslt.transform(RsXslt.java:133)\r\n\tat org.takes.rs.RsXslt.access$100(RsXslt.java:89)\r\n\tat org.takes.rs.RsXslt$1.body(RsXslt.java:113)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.fork.RsFork$1.body(RsFork.java:74)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)\r\n\tat org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)\r\n\tat org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.fork.RsFork$1.body(RsFork.java:74)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)\r\n\t... 23 more\r\nCaused by: ValidationException: Cannot convert string &quot;-1,000&quot; to double\r\n\tat net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:393)\r\n\tat net.sf.saxon.type.ValidationFailure.asAtomic(ValidationFailure.java:419)\r\n\tat net.sf.saxon.expr.sort.UntypedNumericComparer.quickComparison(UntypedNumericComparer.java:159)\r\n\tat net.sf.saxon.expr.sort.UntypedNumericComparer.quickCompare(UntypedNumericComparer.java:59)\r\n\tat net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:833)\r\n\tat net.sf.saxon.expr.GeneralComparison.evaluateManyToOne(GeneralComparison.java:711)\r\n\tat net.sf.saxon.expr.GeneralComparison.effectiveBooleanValue(GeneralComparison.java:660)\r\n\tat net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902)\r\n\tat net.sf.saxon.expr.instruct.Choose.iterate(Choose.java:953)\r\n\tat net.sf.saxon.expr.instruct.BlockIterator.next(BlockIterator.java:49)\r\n\tat net.sf.saxon.tree.iter.AdjacentTextNodeMergingIterator.next(AdjacentTextNodeMergingIterator.java:52)\r\n\tat net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:50)\r\n\tat net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:32)\r\n\tat net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:108)\r\n\tat net.sf.saxon.functions.FoldingFunction.call(FoldingFunction.java:59)\r\n\tat net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:547)\r\n\tat net.sf.saxon.expr.Expression.evaluateItem(Expression.java:831)\r\n\tat net.sf.saxon.expr.Expression.evaluateAsString(Expression.java:890)\r\n\tat net.sf.saxon.expr.instruct.SimpleNodeConstructor.processLeavingTail(SimpleNodeConstructor.java:218)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:262)\r\n\tat net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)\r\n\tat net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)\r\n\tat net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)\r\n\tat net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)\r\n\tat net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)\r\n\tat net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)\r\n\tat net.sf.saxon.trans.Mode.applyTemplates(Mode.java:478)\r\n\tat net.sf.saxon.Controller.transformDocument(Controller.java:2402)\r\n\tat net.sf.saxon.Controller.transform(Controller.java:1970)\r\n\tat net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596)\r\n\tat net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)\r\n\tat org.takes.rs.RsXslt.transform(RsXslt.java:160)\r\n\tat org.takes.rs.RsXslt.transform(RsXslt.java:131)\r\n\t... 45 more\r\n</pre>\n    </body>\n</html>\n"
  TkBoardTest.rendersBoardWithProjectWithoutFunding:94 
Expected: (an XML document with XPath //xhtml:span[@title = 'The project has no funds, you will work for free'])
     but: an XML document with XPath //xhtml:span[@title = 'The project has no funds, you will work for free'] was "<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n    <head>\n        <meta charset=\"utf-8\"/>\n        <title>0crat: error</title>\n        <meta name=\"description\" content=\"Internal application error\"/>\n        <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\"/>\n        <link rel=\"shortcut icon\" href=\"/png/logo.png\"/>\n        <link rel=\"stylesheet\" href=\"/css/main.css\"/>\n        <title>oops...</title>\n    </head>\n    <body>\n        <p>\n            <a href=\"/\">\n                <img src=\"/svg/logo.svg\" class=\"logo\" />\n            </a>\n        </p>\n        <h1>Internal application error</h1>\n        <p>1.0-SNAPSHOT, </p>\n        <p>\n            Please, report it\n            <a href=\"https://github.com/zerocracy/farm/issues\">here</a>.\n            We will do our best to fix it as soon as possible.\n            We're very sorry.\n        </p>\n        <pre>java.lang.IllegalStateException: [GET http://www.example.com/board] failed in 226ms: ValidationException: Cannot convert string &quot;-1,000&quot; to double\r\n\tat org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)\r\n\tat org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)\r\n\tat org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsPrint.printBody(RsPrint.java:161)\r\n\tat org.takes.rs.RsPrint.printBody(RsPrint.java:91)\r\n\tat com.zerocracy.tk.TkBoardTest.firefoxView(TkBoardTest.java:120)\r\n\tat com.zerocracy.tk.TkBoardTest.rendersBoardWithProjectWithoutFunding(TkBoardTest.java:95)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\r\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\r\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\r\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\r\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\nCaused by: java.io.IOException: ValidationException: Cannot convert string &quot;-1,000&quot; to double\r\n\tat org.takes.rs.RsXslt.transform(RsXslt.java:133)\r\n\tat org.takes.rs.RsXslt.access$100(RsXslt.java:89)\r\n\tat org.takes.rs.RsXslt$1.body(RsXslt.java:113)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.fork.RsFork$1.body(RsFork.java:74)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)\r\n\tat org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)\r\n\tat org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.fork.RsFork$1.body(RsFork.java:74)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)\r\n\tat org.takes.rs.RsWrap.body(RsWrap.java:65)\r\n\tat org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)\r\n\t... 23 more\r\nCaused by: ValidationException: Cannot convert string &quot;-1,000&quot; to double\r\n\tat net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:393)\r\n\tat net.sf.saxon.type.ValidationFailure.asAtomic(ValidationFailure.java:419)\r\n\tat net.sf.saxon.expr.sort.UntypedNumericComparer.quickComparison(UntypedNumericComparer.java:159)\r\n\tat net.sf.saxon.expr.sort.UntypedNumericComparer.quickCompare(UntypedNumericComparer.java:59)\r\n\tat net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:833)\r\n\tat net.sf.saxon.expr.GeneralComparison.evaluateManyToOne(GeneralComparison.java:711)\r\n\tat net.sf.saxon.expr.GeneralComparison.effectiveBooleanValue(GeneralComparison.java:660)\r\n\tat net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902)\r\n\tat net.sf.saxon.expr.instruct.Choose.iterate(Choose.java:953)\r\n\tat net.sf.saxon.expr.instruct.BlockIterator.next(BlockIterator.java:49)\r\n\tat net.sf.saxon.tree.iter.AdjacentTextNodeMergingIterator.next(AdjacentTextNodeMergingIterator.java:52)\r\n\tat net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:50)\r\n\tat net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:32)\r\n\tat net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:108)\r\n\tat net.sf.saxon.functions.FoldingFunction.call(FoldingFunction.java:59)\r\n\tat net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:547)\r\n\tat net.sf.saxon.expr.Expression.evaluateItem(Expression.java:831)\r\n\tat net.sf.saxon.expr.Expression.evaluateAsString(Expression.java:890)\r\n\tat net.sf.saxon.expr.instruct.SimpleNodeConstructor.processLeavingTail(SimpleNodeConstructor.java:218)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:262)\r\n\tat net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)\r\n\tat net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)\r\n\tat net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)\r\n\tat net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)\r\n\tat net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)\r\n\tat net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)\r\n\tat net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)\r\n\tat net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)\r\n\tat net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)\r\n\tat net.sf.saxon.trans.Mode.applyTemplates(Mode.java:478)\r\n\tat net.sf.saxon.Controller.transformDocument(Controller.java:2402)\r\n\tat net.sf.saxon.Controller.transform(Controller.java:1970)\r\n\tat net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596)\r\n\tat net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)\r\n\tat org.takes.rs.RsXslt.transform(RsXslt.java:160)\r\n\tat org.takes.rs.RsXslt.transform(RsXslt.java:131)\r\n\t... 45 more\r\n</pre>\n    </body>\n</html>\n"
  TkProfileTest.rendersProfilePageWithoutRateInFirefox:101 
Expected: a string containing "rate</a> is not defined"
     but: was "<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8"/>
        <title>0crat: error</title>
        <meta name="description" content="Internal application error"/>
        <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
        <link rel="shortcut icon" href="/png/logo.png"/>
        <link rel="stylesheet" href="/css/main.css"/>
        <title>oops...</title>
    </head>
    <body>
        <p>
            <a href="/">
                <img src="/svg/logo.svg" class="logo" />
            </a>
        </p>
        <h1>Internal application error</h1>
        <p>1.0-SNAPSHOT, </p>
        <p>
            Please, report it
            <a href="https://github.com/zerocracy/farm/issues">here</a>.
            We will do our best to fix it as soon as possible.
            We're very sorry.
        </p>
        <pre>java.lang.IllegalStateException: [GET http://www.example.com/u/yegor256] failed in 289ms: ValidationException: Cannot convert string &quot;-1,000&quot; to double
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:91)
	at com.zerocracy.tk.profile.TkProfileTest.firefoxView(TkProfileTest.java:128)
	at com.zerocracy.tk.profile.TkProfileTest.rendersProfilePageWithoutRateInFirefox(TkProfileTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: ValidationException: Cannot convert string &quot;-1,000&quot; to double
	at org.takes.rs.RsXslt.transform(RsXslt.java:133)
	at org.takes.rs.RsXslt.access$100(RsXslt.java:89)
	at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 23 more
Caused by: ValidationException: Cannot convert string &quot;-1,000&quot; to double
	at net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:393)
	at net.sf.saxon.type.ValidationFailure.asAtomic(ValidationFailure.java:419)
	at net.sf.saxon.expr.sort.UntypedNumericComparer.quickComparison(UntypedNumericComparer.java:159)
	at net.sf.saxon.expr.sort.UntypedNumericComparer.quickCompare(UntypedNumericComparer.java:59)
	at net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:833)
	at net.sf.saxon.expr.GeneralComparison.evaluateManyToOne(GeneralComparison.java:711)
	at net.sf.saxon.expr.GeneralComparison.effectiveBooleanValue(GeneralComparison.java:660)
	at net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902)
	at net.sf.saxon.expr.instruct.Choose.iterate(Choose.java:953)
	at net.sf.saxon.expr.instruct.BlockIterator.next(BlockIterator.java:49)
	at net.sf.saxon.tree.iter.AdjacentTextNodeMergingIterator.next(AdjacentTextNodeMergingIterator.java:52)
	at net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:50)
	at net.sf.saxon.tree.iter.UntypedAtomizingIterator.next(UntypedAtomizingIterator.java:32)
	at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:108)
	at net.sf.saxon.functions.FoldingFunction.call(FoldingFunction.java:59)
	at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:547)
	at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:831)
	at net.sf.saxon.expr.Expression.evaluateAsString(Expression.java:890)
	at net.sf.saxon.expr.instruct.SimpleNodeConstructor.processLeavingTail(SimpleNodeConstructor.java:218)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:262)
	at net.sf.saxon.expr.instruct.CallTemplate.process(CallTemplate.java:353)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
	at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)
	at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
	at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
	at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
	at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
	at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:478)
	at net.sf.saxon.Controller.transformDocument(Controller.java:2402)
	at net.sf.saxon.Controller.transform(Controller.java:1970)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)
	at org.takes.rs.RsXslt.transform(RsXslt.java:160)
	at org.takes.rs.RsXslt.transform(RsXslt.java:131)
	... 45 more
</pre>
    </body>
</html>
"
Tests in error: 
  TkProfileTest.rendersProfilePageWithRateInFirefox:81 » CashParsing Can't parse...
```
The full build log is here: https://gist.github.com/proshin-roman/74a020cc2beb2f7751628ddcace85cda

Not sure if it's locale-specific issue - maybe somebody else can try to build the project on Windows too.

**Comment by g4s8** [comment]
@proshin-roman so you have only one failing test now (`TkBoardTest`), right? I've made sure that new master is passing tests on Windows on Appveyor: #1178, so it's probably locale-specific issue.

**Comment by proshin-roman** [comment]
@g4s8 `TkProfileTest` is failing too, but due to the same cause: `Cannot convert string &quot;-1,000&quot; to double`.

**Comment by g4s8** [comment]
@proshin-roman can you try again?

**Comment by g4s8** [comment]
@proshin-roman ping. Can you build now?

**Comment by proshin-roman** [comment]
@g4s8 now I have no test failures (according to maven report `Tests run: 399, Failures: 0, Errors: 0, Skipped: 15`) but the build is still failing due to `TestListener` that says:
```
java.lang.IllegalStateException: There were some exceptions in the log above
        at com.zerocracy.TestListener.testRunFinished(TestListener.java:79)
        at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
        at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:63)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```
I guess it finds failures for the tests which pollute the build log by stacktraces with `Cannot convert string "-1,000" to double` message.

May I help you somehow else?

**Comment by krzyk** [comment]
@proshin-roman Could you upload the full build log where it throws such exception?

**Comment by proshin-roman** [comment]
@krzyk I've uploaded it as a gist: https://gist.github.com/proshin-roman/6375ad56eeac773d3253ee8764038ede

**Comment by g4s8** [comment]
@proshin-roman it should be fixed now, please try again

**Comment by proshin-roman** [comment]
@g4s8 The build is still failing: https://gist.github.com/proshin-roman/6375ad56eeac773d3253ee8764038ede (updated the gist)

**Comment by proshin-roman** [comment]
@g4s8 Maybe it will help: systeminfo.exe prints the following info about locale
```
System Locale:             ru;Russian
Input Locale:              ru;Russian
```

**Comment by g4s8** [comment]
@proshin-roman please try again ;) Now it have to build on Windows

**Comment by proshin-roman** [comment]
@g4s8 no, still failing :( https://gist.github.com/proshin-roman/6375ad56eeac773d3253ee8764038ede (updated the gist)

**Comment by rgevaerd** [comment]
@g4s8 @proshin-roman There are locale specific errors. For example, in my Windows, running TkIdentifyTest fails due to 

> Caused by: java.io.IOException: ValidationException: Cannot convert string &quot;-1,000&quot; to double

but running it with  **-Duser.country=US -Duser.language=en** it runs successfully.

**Comment by rgevaerd** [comment]
@g4s8 After forcing the US locale there are only two tests are failing on my Windows: ClaimsItemTest.ignoresClaimsUntilTheyBecomeValid and RbOnCloseTest.registerDelayedClaim. Should I create an issue for each of them? Or that would be part of this issue?

**Comment by g4s8** [comment]
@rgevaerd we already have this job: #1231

**Comment by 0pdd** [comment]
@proshin-roman the puzzle [#1542](https://github.com/zerocracy/farm/issues/1542) is still not solved; solved: [#1231](https://github.com/zerocracy/farm/issues/1231).

**Comment by g4s8** [comment]
@proshin-roman it was partially fixed in #1367 and will be fixed completely after #1704
