### ISSUE TITLE
"Estimated" value is not updated in some projects

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2009]
Some projects complain that their "estimated" value in the dashboard is not updated after they un-assign some tasks. Let's check and fix.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by zverovich** [comment]
Attaching screenshot from the "estimates" page:
![image](https://user-images.githubusercontent.com/6697455/56576965-74e1bf80-65d2-11e9-9030-ed1bde59d41e.png)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2009](https://github.com/zerocracy/farm/issues/2009), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.6`

**Comment by g4s8** [comment]
@yegor256 @zverovich it should be fixed, please check https://www.0crat.com/p/CF9LG1YCA

**Comment by zverovich** [comment]
Confirmed, money is unlocked. But "estimates" page still shows Total: $230.25. and empty list of estimates.

**Comment by g4s8** [comment]
@yegor256 I think we don't need this `total` attribute for estimates document, please see https://github.com/zerocracy/datum/issues/402

**Comment by g4s8** [comment]
@yegor256 it was fixed in https://github.com/zerocracy/farm/commit/c2f6a119ef54ccf98cb567201aabb142b3a14293

**Comment by 0crat** [comment]
Job [#2009](https://github.com/zerocracy/farm/issues/2009) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#2009](https://github.com/zerocracy/farm/issues/2009) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
